### PR TITLE
test(compositor): measure the Linux cursor trail over a one-frame shutter

### PR DESCRIPTION
**Pull request by EtienneLescot**
\`compose_linux_trainee_de_curseur\` fails on main since 34b2e5847 bounded the cursor shutter to one frame (\`trail_dt = blur01 / FPS\`). The test still assumed an 8/60 s trail, so its measurement window was empty.

**Change**
- The cursor moves at 8 cx/s, so the one-frame trail spans ~128 px.
- The window sits between the current sprite and the oldest copy (x 670..738). Threshold 1700 of 2856 px.
- Comments updated to the one-frame shutter.

**Verified** under WSL with lavapipe (local \`Gpu::create_auto\` patch, \`OPENSCREEN_LINUX_COMPOSE=1\`)
- 0834a66c: \`sur le trajet=0\`, fails.
- This branch: \`sur le trajet=2856 bande miroir=0\`, passes.

**Not in scope:** on lavapipe, \`annotation_flou_et_mosaique\`, \`flou_de_velocite_ecran\` and \`sans_camera_ne_dessine_pas_de_vignette\` fail too, identically before and after this change.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

## Summary by CodeRabbit

- **Tests**
  - Improved validation of cursor trails and motion-blur rendering on Linux.
  - Updated test timing and visual measurement criteria to better reflect single-frame blur behavior.
  - Refined pixel-based assertions for more accurate detection of rendered trail output.

### CODE REVIEW

**Comment by EtienneLescot** [comment]
@coderabbitai review

**Comment by EtienneLescot** [comment]
@coderabbitai review

**Comment by EtienneLescot** [comment]
Intégrée dans `integration/chantier-3d` (#682) avec ses corrections de revue CodeRabbit ; le chantier avance désormais dans cette seule PR.
